import React, {useState, useEffect} from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import {isMobile} from 'react-device-detect'

import { TweenLite, gsap } from 'gsap'

import Content04 from '../components/Content04'

const Home: NextPage = () => {  
  const [webglFlag, setWebglFlag] = useState({'flag':false})

  return (
    <div className='w-screen min-h-screen '>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div id='canvas-wrapper'
        className='relative top-0 left-0 w-screen h-screen pointer-events-auto'
      >
          <canvas id='webgl-canvas' className='w-screen h-screen'/>
      </div>
      <Content04/>
    </div>
  )
}

export default Home
